import type { TopicContent } from "./types";

export const artificialIntelligence: TopicContent = {
  slug: "artificial-intelligence",
  hero:
    "Artificial Intelligence is reshaping society — from spam filters to self-driving cars to autonomous weapons. This module unpacks what AI really is, how machine learning works, the limits of narrow AI, the dangers of algorithmic bias and the deep question of who is responsible when AI gets it wrong.",
  tags: ["AI", "MACHINE LEARNING", "NARROW AI", "ROBOTS", "BIAS", "RESPONSIBILITY"],
  sections: [
    {
      id: "ai-ml",
      code: "01",
      title: "AI & Machine Learning",
      explanation:
        "Artificial Intelligence (AI) is the simulation of human intelligence by computer systems. Machine learning (ML) is the branch of AI where systems learn from data rather than being explicitly programmed.",
      bullets: [
        "AI = simulation of human intelligence by computer systems (perception, reasoning, learning).",
        "Machine learning = systems learn from data rather than being programmed for every rule.",
        "ML systems analyse real-time and historical data.",
        "ML systems detect patterns in data.",
        "ML systems improve automatically as they receive more data.",
        "ML does not require explicit programming for every rule or situation.",
        "Robots are programmable machines that carry out physical actions, often using AI.",
      ],
      paragraphs: [
        "Traditional programming follows fixed rules a developer writes. ML flips this around: you give the system many examples (training data) and it builds its own rules to make predictions or decisions on new data it has never seen.",
        "Because ML improves with more data, the systems get more accurate over time — but they also inherit the strengths and weaknesses of whatever data they were trained on.",
        "Robots combine AI software with physical hardware: sensors, actuators and motors. Industrial robots build cars, surgical robots assist operations, and domestic robots vacuum floors.",
      ],
      quiz: [
        { q: "AI =", options: ["Simulation of human intelligence by computers", "Always Internet", "A new language", "A type of cable"], answer: 0, why: "Definition." },
        { q: "ML systems improve by…", options: ["Receiving more data", "Being unplugged", "Going offline", "Stopping training"], answer: 0, why: "Data-driven learning." },
        { q: "ML does NOT require…", options: ["Explicit programming for every rule", "Data", "Training", "Patterns"], answer: 0, why: "It learns patterns itself." },
        { q: "Robots combine AI with…", options: ["Physical hardware", "Only books", "Only databases", "Only humans"], answer: 0, why: "Sensors + actuators." },
        { q: "Training data is used to…", options: ["Teach the model patterns", "Run the OS", "Cool the CPU", "Print labels"], answer: 0, why: "Examples shape the model." },
        { q: "Traditional programming uses…", options: ["Fixed rules", "Self-learned rules", "No rules", "Random rules"], answer: 0, why: "Developer-written rules." },
        { q: "ML can analyse…", options: ["Real-time and historical data", "Only paper", "Only audio", "Only voice"], answer: 0, why: "Both streams." },
        { q: "True/False: ML systems detect patterns.", options: ["True", "False"], answer: 0, why: "Core capability." },
        { q: "Example of robot using AI?", options: ["Self-driving car", "Hammer", "Pen", "Spoon"], answer: 0, why: "Sensor-rich, AI-driven machine." },
        { q: "ML accuracy generally…", options: ["Improves with more relevant data", "Decreases with data", "Never changes", "Drops to zero"], answer: 0, why: "More data = better patterns (if quality)." },
      ],
    },
    {
      id: "narrow-ai",
      code: "02",
      title: "Narrow AI",
      explanation:
        "Narrow (or 'weak') AI is built to perform one specific task very well. It cannot generalise. Almost every real-world AI in 2026 is narrow AI.",
      bullets: [
        "Narrow AI performs ONE specific task.",
        "Examples: spam filters that classify email.",
        "Examples: social media monitoring (content moderation).",
        "Examples: facial recognition (unlock phones, surveillance).",
        "Examples: fingerprint recognition (security access).",
        "Examples: recommendation systems (Netflix, YouTube, Spotify).",
        "Examples: voice assistants (Siri, Alexa, Google Assistant).",
        "Examples: self-driving cars (perception + control).",
        "Examples: lethal autonomous weapons (military drones).",
        "Narrow AI fails outside its designed problem space.",
      ],
      paragraphs: [
        "A spam filter is brilliant at sorting email but cannot drive a car; a self-driving model cannot recommend movies. Each system is tightly specialised — feed it the wrong problem and the results are nonsense.",
        "Lethal autonomous weapons are one of the most controversial uses of narrow AI: machines deciding which target to engage without human approval raises severe ethical and legal concerns.",
      ],
      quiz: [
        { q: "Narrow AI is…", options: ["Specialised in one task", "Good at everything", "Truly conscious", "Random"], answer: 0, why: "Single-task focus." },
        { q: "Which is NOT a narrow-AI example?", options: ["Spam filter", "Facial recognition", "Voice assistant", "Conscious general thinker"], answer: 3, why: "That would be AGI, not narrow AI." },
        { q: "Self-driving cars are…", options: ["Narrow AI", "General AI", "Not AI", "Just rules"], answer: 0, why: "Specialised perception/control task." },
        { q: "Recommendation systems suggest…", options: ["Content based on patterns", "Random items always", "Government laws", "School subjects"], answer: 0, why: "Pattern-based suggestions." },
        { q: "Voice assistants do…", options: ["Speech recognition + responses", "Plumbing", "Plant trees", "Drive trains"], answer: 0, why: "Narrow speech task." },
        { q: "Lethal autonomous weapons are…", options: ["Controversial narrow AI", "Toys", "Cookware", "Sports gear"], answer: 0, why: "Military narrow AI." },
        { q: "Narrow AI fails…", options: ["Outside its designed task", "Inside its task", "Never", "Always"], answer: 0, why: "Doesn't generalise." },
        { q: "Spam filters classify…", options: ["Emails", "Cars", "Animals", "Trees"], answer: 0, why: "Text classification." },
        { q: "Fingerprint recognition is used for…", options: ["Security access", "Voice typing", "Driving", "Cooking"], answer: 0, why: "Biometric login." },
        { q: "Social media monitoring helps…", options: ["Moderate content", "Build engines", "Make food", "Mine ore"], answer: 0, why: "Auto-flagging content." },
      ],
    },
    {
      id: "bias",
      code: "03",
      title: "Algorithmic Bias",
      explanation:
        "Algorithmic bias happens when an AI system produces unfair or discriminatory outcomes — often without anyone intending it. The bias comes from the data, the algorithm or the developers.",
      bullets: [
        "Cause 1: biased training data — historical data reflects past prejudices.",
        "Cause 2: flawed algorithms — design choices amplify certain patterns.",
        "Cause 3: developer prejudice — conscious or unconscious bias in the team.",
        "AI systems may discriminate unfairly (jobs, loans, policing, healthcare).",
        "Bias is often invisible until outcomes are studied at scale.",
      ],
      paragraphs: [
        "If a hiring AI is trained on 20 years of company hiring data and that company hired mostly men, the AI will learn that 'good candidates look like the men who were hired before' and downrank women. The data itself encodes the bias.",
        "Even with neutral data, design choices — what counts as success, what features are used — can amplify bias. And the developers themselves bring assumptions into how the system is built and tested.",
        "Real-world consequences are severe: biased facial recognition has misidentified innocent people; biased risk-scoring has unfairly denied loans or parole.",
      ],
      quiz: [
        { q: "Algorithmic bias =", options: ["Unfair outcomes from AI systems", "Faster algorithms", "Random results", "Better fairness"], answer: 0, why: "Definition." },
        { q: "A cause of bias?", options: ["Biased training data", "Better Wi-Fi", "More RAM", "Bigger screen"], answer: 0, why: "Garbage in, biased out." },
        { q: "Flawed algorithms can…", options: ["Amplify bias", "Cure bias", "Add nothing", "Erase data"], answer: 0, why: "Design choices matter." },
        { q: "Developer prejudice means…", options: ["Conscious/unconscious bias from the team", "Better tests", "Cleaner code", "Free hardware"], answer: 0, why: "Human bias in process." },
        { q: "Biased AI may discriminate in…", options: ["Jobs, loans, policing, healthcare", "Sports only", "Cooking only", "Weather only"], answer: 0, why: "Real-world harm." },
        { q: "Bias is often invisible until…", options: ["Outcomes studied at scale", "First test", "Never", "Power off"], answer: 0, why: "Discovered through audits." },
        { q: "Historical hiring data may…", options: ["Encode past prejudices", "Be perfectly fair", "Train chess AI", "Build hardware"], answer: 0, why: "Past patterns continue." },
        { q: "Biased facial recognition has…", options: ["Misidentified innocent people", "Always worked perfectly", "Cured bias", "Removed all errors"], answer: 0, why: "Documented harm." },
        { q: "True/False: bias can come from data, algorithm AND developers.", options: ["True", "False"], answer: 0, why: "Three main sources." },
        { q: "To fix bias you need…", options: ["Better data + design + diverse teams + audits", "Just more data", "Just speed", "Just bigger model"], answer: 0, why: "Multi-pronged response." },
      ],
    },
    {
      id: "responsibility",
      code: "04",
      title: "Responsibility & Accountability",
      explanation:
        "When an AI system causes harm, who is responsible? The creator, the data supplier, the user, or 'the algorithm'? This is one of the biggest open problems in AI law and ethics.",
      bullets: [
        "Creator responsibility — those who designed and built the system.",
        "Training data supplier responsibility — bad or biased data → harmful behaviour.",
        "User responsibility — how the system is deployed and supervised.",
        "'Black-box' systems hide their reasoning, making responsibility harder to trace.",
        "Lack of explainability makes legal accountability difficult.",
      ],
      paragraphs: [
        "A 'black-box' AI gives outputs without showing why. Deep neural networks are powerful but notoriously hard to explain. If a black-box loan model rejects you, it can be impossible to challenge the decision, because nobody (including the bank) fully understands the reasoning.",
        "Accountability typically splits across all three parties. The creator should design safely; the data supplier should provide unbiased, representative data; the user must deploy responsibly with oversight. Regulators are pushing for 'explainable AI' to make this chain of responsibility workable in law.",
      ],
      quiz: [
        { q: "If AI harms someone, responsibility may lie with…", options: ["Creator, data supplier, user", "Only the keyboard", "Only the screen", "Nobody ever"], answer: 0, why: "Shared chain." },
        { q: "Black-box AI is hard to…", options: ["Explain its reasoning", "Boot up", "Turn off", "Build"], answer: 0, why: "Opaque decision-making." },
        { q: "Training data supplier is responsible for…", options: ["Quality and bias of data", "Wi-Fi speed", "Hardware costs", "Marketing"], answer: 0, why: "Garbage in, garbage out." },
        { q: "Users are responsible for…", options: ["Deployment + oversight", "Writing the kernel", "Mining metals", "Fixing servers"], answer: 0, why: "Real-world use matters." },
        { q: "Explainable AI aims to…", options: ["Make reasoning understandable", "Be slower", "Be black-box", "Refuse outputs"], answer: 0, why: "Transparency for accountability." },
        { q: "Hardest case of accountability?", options: ["Black-box harming someone", "Calculator giving 2+2", "Light bulb on", "Notepad app"], answer: 0, why: "Opaque + harmful." },
        { q: "Lack of explainability creates…", options: ["Legal accountability problems", "Free phones", "Better Wi-Fi", "More speed"], answer: 0, why: "Can't trace fault." },
        { q: "Creator's duty includes…", options: ["Safe design and testing", "Free updates forever", "Free hardware", "Free training data"], answer: 0, why: "Design responsibility." },
        { q: "True/False: 'the algorithm did it' is a strong legal defence.", options: ["True", "False"], answer: 1, why: "Courts assign liability to humans/orgs." },
        { q: "Most responsible approach?", options: ["Shared accountability + explainable AI + audits", "Blame the user only", "Blame nobody", "Use only black-box"], answer: 0, why: "Combined safeguards." },
      ],
    },
  ],
  flashcards: [
    { category: "AI", front: "AI definition", back: "Simulation of human intelligence by computer systems — perception, reasoning, learning." },
    { category: "ML", front: "Machine learning", back: "Systems that learn from data and improve automatically rather than being explicitly programmed for every rule." },
    { category: "NARROW AI", front: "Narrow AI", back: "AI specialised in one task — fails outside its designed problem space." },
    { category: "NARROW AI", front: "Narrow AI examples", back: "Spam filters, social media monitoring, facial/fingerprint recognition, recommendations, voice assistants, self-driving cars, lethal autonomous weapons." },
    { category: "BIAS", front: "Causes of algorithmic bias", back: "Biased training data, flawed algorithms, developer prejudice." },
    { category: "BIAS", front: "Impact of bias", back: "Unfair discrimination in jobs, loans, policing, healthcare and more." },
    { category: "RESPONSIBILITY", front: "Who is responsible for AI harm?", back: "Creator, training data supplier, user — shared accountability." },
    { category: "RESPONSIBILITY", front: "Black-box AI", back: "AI whose internal reasoning is hidden/opaque — makes accountability and legal challenge much harder." },
  ],
};
