import type { TopicContent } from "./types";

export const environmentalIssues: TopicContent = {
  slug: "environmental-issues",
  hero:
    "Every digital device carries a hidden environmental cost — from the mines where its metals are extracted, through factories and data centres, to the landfill where it eventually rots. This module decodes the full footprint of computing and the laws, behaviours and technologies that can reduce it.",
  tags: ["MANUFACTURE", "ENERGY", "DISPOSAL", "WEEE", "RECYCLING", "REPLACEMENT", "REDUCE", "POSITIVE"],
  sections: [
    {
      id: "manufacture",
      code: "01",
      title: "Manufacture",
      explanation:
        "Producing a digital device requires huge amounts of raw materials, energy and water — long before the device is ever switched on. The environmental cost of a phone or laptop begins inside a mine.",
      bullets: [
        "Digital devices need raw materials such as copper, palladium and arsenic.",
        "Copper and palladium are non-renewable — Earth has a finite supply that cannot be replaced fast enough once used.",
        "Arsenic is highly toxic and dangerous to handle.",
        "Mining scars landscapes, creates waste, destroys wildlife habitats and damages ecosystems.",
        "Manufacturing consumes huge amounts of energy, most of it from fossil fuels (non-renewable).",
        "Burning fossil fuels releases CO₂, accelerating global warming and climate change.",
        "Factories produce polluted waste water containing toxic chemicals that can enter rivers and lakes.",
        "Technology production has environmental costs BEFORE devices are even turned on.",
      ],
      paragraphs: [
        "Mining for the metals inside a phone strips topsoil, diverts rivers and leaves behind huge open pits. Local wildlife loses its habitat and surrounding communities often lose access to clean water. Copper and palladium are essential for circuitry, but their supply is finite — once extracted, the planet cannot regenerate them on any useful timescale.",
        "Silicon chips are produced in cleanrooms that need vast amounts of ultra-pure water and electricity. A single chip factory can use as much power as a small city, and most of that electricity still comes from non-renewable fossil fuels, contributing directly to climate change.",
        "Waste water from chip plants and metal refineries can contain heavy metals, arsenic and solvents. If it is not treated properly it leaks into rivers and lakes, killing fish and contaminating drinking water for years afterwards.",
      ],
      quiz: [
        { q: "Which raw material used in devices is highly toxic?", options: ["Copper", "Palladium", "Arsenic", "Aluminium"], answer: 2, why: "Arsenic is toxic and dangerous to handle." },
        { q: "Why is copper described as non-renewable?", options: ["It rusts away", "Earth has a finite supply that cannot regrow", "It is illegal to mine", "It evaporates"], answer: 1, why: "Non-renewable = finite, not replaced quickly by nature." },
        { q: "Mining for materials mainly damages…", options: ["The internet", "Wildlife habitats and ecosystems", "Software performance", "Server uptime"], answer: 1, why: "Strip mining destroys habitats." },
        { q: "Most electricity used in manufacturing comes from…", options: ["Solar", "Wind", "Fossil fuels", "Tidal"], answer: 2, why: "Most global grids still rely on fossil fuels." },
        { q: "Burning fossil fuels contributes to…", options: ["Faster Wi-Fi", "Climate change", "Cheaper devices", "Battery life"], answer: 1, why: "CO₂ drives global warming." },
        { q: "Polluted factory waste water can…", options: ["Improve ecosystems", "Damage rivers and lakes", "Make rain cleaner", "Cool the planet"], answer: 1, why: "Toxic chemicals harm aquatic life." },
        { q: "A phone has environmental costs…", options: ["Only when used", "Even before it is turned on", "Only when recycled", "Never"], answer: 1, why: "Mining and manufacture happen first." },
        { q: "Which is NOT a typical manufacturing impact?", options: ["Energy use", "Toxic waste water", "Habitat loss", "Reduced e-waste"], answer: 3, why: "Manufacturing increases e-waste pressure." },
        { q: "Palladium is…", options: ["Renewable", "Non-renewable", "A gas", "Edible"], answer: 1, why: "Finite supply." },
        { q: "Why does mining damage ecosystems?", options: ["Removes habitats and pollutes water", "Plants trees", "Feeds animals", "Cools climate"], answer: 0, why: "Vegetation lost, water contaminated." },
      ],
    },
    {
      id: "energy",
      code: "02",
      title: "Energy Consumption",
      explanation:
        "Digital technology consumes electricity at every stage of its life: producing devices, operating them, storing data in data centres, and recycling them. Most of that energy is used away from the user.",
      bullets: [
        "Energy is consumed during production, operation, online data storage and recycling.",
        "Manufacture + disposal ≈ 70% of lifetime energy (mining, manufacturing, packaging, transport, recycling).",
        "Use ≈ 30% of lifetime energy (powering devices, telecoms networks, storing data).",
        "Data centres run 24/7 storing and serving huge amounts of data.",
        "Telecoms networks (masts, routers, undersea cables) consume continuous power.",
        "Cooling servers can use almost as much energy as the servers themselves.",
        "Most energy is consumed BEFORE and AFTER use, not during use itself.",
        "Technology can REDUCE energy use elsewhere: smart lighting, route planners, light sensors, intelligent systems.",
      ],
      paragraphs: [
        "When you stream a video, energy is consumed by your phone, the data centre serving the video, the network carrying it, and the cooling system stopping the servers overheating. The visible part is tiny compared to the hidden infrastructure.",
        "Because manufacture + transport + recycling dominate the lifetime footprint, keeping a device longer is often greener than upgrading to a 'more efficient' new one — the new device's production cost outweighs years of efficiency savings.",
        "Technology can also CUT energy elsewhere. Smart lighting only powers occupied rooms, route planners reduce wasted fuel, intelligent grids balance renewable supply with demand, and light sensors prevent unnecessary illumination.",
      ],
      quiz: [
        { q: "Roughly what % of lifetime energy is used in manufacture + disposal?", options: ["10%", "30%", "70%", "90%"], answer: 2, why: "About 70%." },
        { q: "Use accounts for roughly…", options: ["30%", "70%", "5%", "95%"], answer: 0, why: "About 30%." },
        { q: "Cooling in data centres…", options: ["Is negligible", "Can use almost as much energy as servers", "Uses no power", "Is illegal"], answer: 1, why: "Major operating cost." },
        { q: "Data centres typically run…", options: ["At night only", "24/7", "Weekdays only", "On demand briefly"], answer: 1, why: "Always-on services." },
        { q: "Which REDUCES energy use through tech?", options: ["Smart lighting", "Bigger screens", "Brighter displays", "Always-on GPS"], answer: 0, why: "Only powers when needed." },
        { q: "Route planners help by…", options: ["Adding traffic", "Reducing wasted fuel", "Burning more petrol", "Stopping deliveries"], answer: 1, why: "Shorter routes = less fuel." },
        { q: "Why is 'use' only ~30% of footprint?", options: ["Manufacture and disposal dominate", "Charging is free", "Devices are off", "Software is light"], answer: 0, why: "Production/end-of-life dominate." },
        { q: "Light sensors save energy by…", options: ["Always staying on", "Turning lights off when not needed", "Boosting brightness", "Burning fuel"], answer: 1, why: "Prevents wasted electricity." },
        { q: "Telecoms networks consume…", options: ["No power", "Continuous 24/7 power", "Power only when phones ring", "Solar only"], answer: 1, why: "Masts and cables always-on." },
        { q: "Streaming HD video uses energy…", options: ["Only on your phone", "On phone + data centre + network + cooling", "Nowhere", "Only in browsers"], answer: 1, why: "Whole chain consumes power." },
      ],
    },
    {
      id: "disposal",
      code: "03",
      title: "Disposal & E-waste",
      explanation:
        "Discarded digital devices become e-waste. The world produces around 50 million tonnes of it every year and only about 20% is properly recycled. The rest causes serious environmental and human harm.",
      bullets: [
        "Approximately 50 million tonnes of e-waste produced globally per year.",
        "Only around 20% is recycled responsibly.",
        "Illegal dumping in landfill causes toxic chemicals to leak: lead, mercury and cobalt contamination.",
        "Chemicals enter soil, groundwater and rivers.",
        "People living near e-waste dumps suffer poisoning, disease and long-term health problems.",
        "Many people in poorer countries salvage valuable materials from dangerous waste sites.",
        "Millions of tonnes of e-waste are dumped in developing countries every year.",
      ],
      paragraphs: [
        "Many electronics are dumped illegally in landfill sites in poorer countries. Local workers — sometimes children — burn cables to recover copper, exposing themselves to highly toxic fumes containing lead, mercury and dioxins.",
        "Heavy metals such as lead, mercury and cobalt leak slowly into the soil. Once in groundwater they are extremely difficult to remove and can poison drinking water for entire communities for decades.",
        "Long-term exposure causes serious illness, including neurological damage, organ failure and cancers. Illegal e-waste dumping causes major environmental and human harm — the human cost of careless disposal is enormous compared to the small effort of recycling responsibly.",
      ],
      quiz: [
        { q: "Approx e-waste per year globally?", options: ["5 Mt", "20 Mt", "50 Mt", "500 Mt"], answer: 2, why: "~50 million tonnes." },
        { q: "Roughly what % is properly recycled?", options: ["20%", "50%", "75%", "95%"], answer: 0, why: "Only ~20%." },
        { q: "Which chemicals commonly leak from e-waste?", options: ["Sugar and salt", "Lead, mercury, cobalt", "Oxygen, nitrogen", "Iron and zinc only"], answer: 1, why: "Toxic heavy metals." },
        { q: "E-waste contamination ends up in…", options: ["The cloud", "Soil and groundwater", "Outer space", "Books"], answer: 1, why: "Leaches into ground/water." },
        { q: "Communities near dumpsites often suffer…", options: ["Better internet", "Poisoning and disease", "Cheaper bills", "Cleaner water"], answer: 1, why: "Chronic exposure illness." },
        { q: "Why salvage e-waste despite the danger?", options: ["It's safe and fun", "Recover valuable materials", "Government orders", "School requirement"], answer: 1, why: "Poverty + valuable metals." },
        { q: "Which is NOT a consequence of illegal dumping?", options: ["Soil pollution", "Water contamination", "Improved biodiversity", "Health problems"], answer: 2, why: "It reduces biodiversity." },
        { q: "E-waste decomposes safely like food?", options: ["True", "False"], answer: 1, why: "Non-biodegradable and toxic." },
        { q: "Where is much e-waste exported to?", options: ["The Moon", "Developing countries", "Deep sea only", "Nowhere"], answer: 1, why: "Wealthier nations export it." },
        { q: "E-waste means…", options: ["Spam emails", "Discarded electronic devices", "Old PDFs", "Used USB cables only"], answer: 1, why: "Any discarded electrical/electronic equipment." },
      ],
    },
    {
      id: "weee",
      code: "04",
      title: "WEEE Regulations",
      explanation:
        "The WEEE regulations (Waste Electrical and Electronic Equipment) are designed to reduce environmental harm from discarded electronics by forcing producers and retailers to collect, recycle and recover them properly.",
      bullets: [
        "WEEE = Waste Electrical and Electronic Equipment regulations.",
        "Set legal recycling targets.",
        "Set legal collection targets.",
        "Encourage recovery of valuable electronic components.",
        "Purpose: reduce environmental harm caused by e-waste.",
        "Retailers must offer take-back schemes for old equipment.",
      ],
      paragraphs: [
        "Before WEEE, manufacturers had no real responsibility for what happened to a product after it was sold. The regulations force them to fund proper collection and recycling, placing the cost where it belongs.",
        "Targets are set for the proportion of electronics that must be collected and recycled each year. Failing to meet them carries large fines, so producers actively support recycling networks and consumer take-back schemes.",
      ],
      quiz: [
        { q: "WEEE stands for…", options: ["World Electrical Energy Exchange", "Waste Electrical and Electronic Equipment", "Wireless Edge Electronics Effort", "Web Electronic Engineering Ethics"], answer: 1, why: "Definition." },
        { q: "WEEE sets targets for…", options: ["Mining metals", "Recycling and collection of electronics", "Game design", "Marketing budgets"], answer: 1, why: "Collection + recycling." },
        { q: "WEEE encourages…", options: ["Quick dumping", "Recovery of electronics", "Illegal export", "Burning waste"], answer: 1, why: "Recovery is key." },
        { q: "Main purpose of WEEE?", options: ["Help advertisers", "Reduce environmental harm of e-waste", "Speed up Wi-Fi", "Lower phone prices"], answer: 1, why: "Stated purpose." },
        { q: "WEEE puts no responsibility on producers?", options: ["True", "False"], answer: 1, why: "It places legal duty on producers/retailers." },
        { q: "Retailers must…", options: ["Refuse old electronics", "Offer take-back of old equipment", "Burn old phones", "Send waste to landfill"], answer: 1, why: "Take-back schemes required." },
        { q: "If targets are missed…", options: ["Nothing", "Producers can be fined", "Customers go to prison", "Devices get cheaper"], answer: 1, why: "Penalties drive compliance." },
        { q: "WEEE applies to…", options: ["Only fridges", "Electrical and electronic equipment", "Only mobiles", "Books"], answer: 1, why: "Broad scope." },
        { q: "WEEE is a…", options: ["Game", "Set of regulations", "Phone brand", "Logo only"], answer: 1, why: "Regulatory framework." },
        { q: "WEEE helps achieve…", options: ["More mining", "More landfill", "Safer disposal and resource recovery", "Faster batteries"], answer: 2, why: "Goal: safer recycling." },
      ],
    },
    {
      id: "recycling",
      code: "05",
      title: "Responsible Recycling",
      explanation:
        "Responsible recycling recovers valuable materials, prevents pollution and reduces the need to mine new resources. It conserves resources and reduces pollution at every stage.",
      bullets: [
        "Reduces chemical leakage into soil and water.",
        "Lowers landfill fire risks (lithium batteries can ignite).",
        "Recovers valuable metals such as gold, copper and aluminium.",
        "Reduces the need for fresh mining.",
        "Allows plastics to be recycled instead of decomposing into harmful toxic particles.",
        "Reduces toxic air pollution from burning waste.",
      ],
      paragraphs: [
        "Modern recycling plants can recover precious metals at higher purity than fresh mining. A single tonne of phones contains more gold than a tonne of typical gold ore.",
        "Without responsible recycling, plastics from devices slowly break down into microplastics that enter the food chain. Burning them releases dioxins and other toxic gases into the air, harming people and wildlife.",
      ],
      quiz: [
        { q: "Responsible recycling helps reduce…", options: ["Mining demand", "Internet speed", "Cricket scores", "Battery sizes"], answer: 0, why: "Recovered metals reduce new mining." },
        { q: "Which is NOT a benefit of recycling?", options: ["Less pollution", "Resource recovery", "More landfill use", "Lower fire risk"], answer: 2, why: "Recycling reduces landfill." },
        { q: "Why are lithium batteries dangerous in landfill?", options: ["Radioactive", "Can catch fire", "Explode in sunlight", "Magnetic"], answer: 1, why: "Lithium cells can ignite." },
        { q: "Common recovered metals?", options: ["Gold, copper, aluminium", "Mercury and lead only", "Silicon only", "Iron only"], answer: 0, why: "Precious + base metals." },
        { q: "Plastics in landfill can…", options: ["Decompose safely", "Decompose into toxic particles", "Turn into wood", "Boost soil"], answer: 1, why: "Microplastics + toxins." },
        { q: "Burning e-waste produces…", options: ["Fresh air", "Toxic air pollution", "Drinking water", "Solar panels"], answer: 1, why: "Dioxins, metals released." },
        { q: "Recovered metals can be…", options: ["Sold abroad only", "Reused in new electronics", "Buried again", "Eaten"], answer: 1, why: "Re-enter supply chain." },
        { q: "Recycling reduces toxic chemical leakage?", options: ["True", "False"], answer: 0, why: "Proper processing isolates toxins." },
        { q: "Compared with mining, recycling is…", options: ["More destructive", "Less damaging", "Identical", "More expensive always"], answer: 1, why: "Lower footprint." },
        { q: "'Closed loop' lifecycle means…", options: ["Wasting more", "Reusing materials repeatedly", "One-time use only", "No recycling"], answer: 1, why: "Materials cycle back." },
      ],
    },
    {
      id: "cycle",
      code: "06",
      title: "Short Replacement Cycle",
      explanation:
        "Most users replace mobile phones roughly every 3 years. The same is true of tablets, smart watches and laptops. This short cycle is encouraged by both consumer desire and manufacturer design choices — sometimes called planned obsolescence.",
      bullets: [
        "Mobile phones are replaced roughly every 3 years on average.",
        "Tablets, smart watches and laptops follow similar short cycles.",
        "Main cause: people want the newest technology models.",
        "Manufacturers embed batteries that are difficult to replace.",
        "Components are glued or soldered, making repair hard.",
        "Spare parts are expensive.",
        "Software and security updates are often stopped after a few years.",
        "Planned obsolescence = deliberately designing products to have a short useful life.",
      ],
      paragraphs: [
        "Embedded batteries, glued screens and soldered storage all push owners toward replacement instead of repair. When the battery weakens after 2–3 years, replacing it costs nearly as much as a new device.",
        "When manufacturers stop providing security updates, older devices become unsafe to use online — even if the hardware still works perfectly. This is one of the most powerful drivers of replacement.",
      ],
      quiz: [
        { q: "Average mobile replacement is roughly every…", options: ["3 months", "3 years", "10 years", "20 years"], answer: 1, why: "~3 years." },
        { q: "Main cause of short cycle?", options: ["People want newest tech", "Phones explode", "Schools ban old ones", "WiFi forces upgrades"], answer: 0, why: "Consumer demand for newest." },
        { q: "Embedded batteries are…", options: ["Easy to swap", "Difficult to replace", "Removable instantly", "Optional"], answer: 1, why: "Sealed inside devices." },
        { q: "Planned obsolescence means…", options: ["Designing devices to fail/expire quickly", "Free upgrades forever", "Eternal devices", "Better recycling"], answer: 0, why: "Deliberately short life." },
        { q: "Software updates ending makes devices…", options: ["Faster", "Less secure online", "More valuable", "Greener"], answer: 1, why: "No security patches." },
        { q: "Spare parts are typically…", options: ["Cheap", "Expensive", "Free", "Banned"], answer: 1, why: "Discourages repair." },
        { q: "Glued components mean…", options: ["Easier repair", "Harder repair", "No effect", "Better recycling"], answer: 1, why: "Hard to open without damage." },
        { q: "Which is NOT replaced on a ~3 yr cycle?", options: ["Phones", "Tablets", "Smart watches", "Bricks"], answer: 3, why: "Self-evident." },
        { q: "Short cycle leads to…", options: ["Less e-waste", "More e-waste, mining, energy use", "Lower pollution", "More forests"], answer: 1, why: "Replacement drives waste." },
        { q: "Manufacturers often encourage…", options: ["Repair", "Replacement", "Composting", "Walking"], answer: 1, why: "Replacement = revenue." },
      ],
    },
    {
      id: "ownership",
      code: "07",
      title: "Responsible Ownership",
      explanation:
        "Users can reduce environmental impact through responsible ownership. Every device kept longer or reused is one less mined, manufactured, shipped and discarded.",
      bullets: [
        "Keeping devices for longer reduces demand for new ones.",
        "Buying second-hand devices reuses existing hardware.",
        "Donating devices extends their useful life.",
        "Recycling properly through WEEE channels keeps toxins out of landfill.",
        "Reducing internet usage cuts data-centre and network energy.",
        "Using energy-efficiency settings lowers power draw.",
      ],
      paragraphs: [
        "Responsible ownership flips the script on planned obsolescence. By treating devices as long-term tools rather than fashion accessories, users directly cut mining, manufacturing energy and e-waste.",
        "Donating still-working devices to charities or schools gives them a second life. Reducing internet streaming quality, closing unused tabs and lowering brightness all cut energy at scale when millions of users do it.",
      ],
      quiz: [
        { q: "Responsible ownership includes…", options: ["Replacing yearly", "Keeping devices longer", "Burning old phones", "Burying in garden"], answer: 1, why: "Longer life = lower impact." },
        { q: "Buying second-hand devices…", options: ["Wastes resources", "Reuses existing hardware", "Increases mining", "Is illegal"], answer: 1, why: "Avoids new production." },
        { q: "Donating devices…", options: ["Helps environment + others", "Causes pollution", "Is banned", "Costs the climate"], answer: 0, why: "Extends life and helps people." },
        { q: "Recycling properly means…", options: ["Through WEEE channels", "In rivers", "Burning in garden", "Bury secretly"], answer: 0, why: "Authorised routes." },
        { q: "Reducing internet use cuts…", options: ["Data centre and network energy", "Sunlight", "Phone weight", "RAM"], answer: 0, why: "Less data, less energy." },
        { q: "Energy-efficiency settings…", options: ["Increase power use", "Lower power draw", "Brick the phone", "Have no effect"], answer: 1, why: "Reduce consumption." },
        { q: "Most user-level action?", options: ["Mine more metals", "Buy yearly", "Keep, donate, recycle, save energy", "Burn devices"], answer: 2, why: "Combined responsible ownership." },
        { q: "Responsible ownership best fights…", options: ["Planned obsolescence", "Healthy soil", "Recycling", "WEEE"], answer: 0, why: "Counters short cycles." },
        { q: "Long-kept devices cause…", options: ["Less mining + manufacturing", "More e-waste", "More pollution", "More energy use"], answer: 0, why: "Avoids new production." },
        { q: "True/False: small user choices add up globally.", options: ["True", "False"], answer: 0, why: "Billions of users x small savings = big impact." },
      ],
    },
    {
      id: "reduce",
      code: "08",
      title: "Reducing Energy Consumption",
      explanation:
        "There are many practical ways to cut the energy used by digital devices. Each method either lowers the device's power draw, switches off unused features, or moves consumption to cleaner sources.",
      bullets: [
        "Lowering screen brightness — display is the biggest battery drain.",
        "Sleep mode — cuts power when idle.",
        "Turning off Bluetooth — stops radio scanning.",
        "Disabling Wi-Fi when not needed — saves continuous radio activity.",
        "Disabling GPS — location tracking is energy-hungry.",
        "Closing dormant applications — they consume CPU and RAM in the background.",
        "Disconnecting peripherals — USB devices, external drives and chargers draw power.",
        "Buying energy-efficient devices (lower TDP, efficient SoCs).",
        "Choosing services hosted in renewable-energy data centres.",
      ],
      paragraphs: [
        "Screens dominate device energy use; halving brightness can nearly double battery life. Disabling radios (Wi-Fi, Bluetooth, GPS) cuts background scanning that runs even when the screen is off.",
        "Dormant apps continue to fetch data, sync and run timers. Closing them, or denying background access, removes hidden energy drain. At a larger scale, choosing cloud services that run on renewable-powered data centres shifts the underlying grid demand toward clean sources.",
      ],
      quiz: [
        { q: "Biggest battery drain is usually…", options: ["The screen", "The case", "The logo", "The SIM"], answer: 0, why: "Display dominates." },
        { q: "Sleep mode…", options: ["Increases power use", "Cuts power when idle", "Brightens screen", "Disables battery"], answer: 1, why: "Reduces draw." },
        { q: "Turning off Bluetooth saves energy because…", options: ["It stops radio scanning", "It removes apps", "It cools the CPU", "It deletes files"], answer: 0, why: "Bluetooth scans continuously." },
        { q: "Disabling GPS…", options: ["Helps as GPS is energy-hungry", "Has no effect", "Charges battery", "Locks phone"], answer: 0, why: "Location tracking drains power." },
        { q: "Closing dormant apps…", options: ["Wastes more energy", "Frees CPU/RAM and saves energy", "Reformats SSD", "Has no impact"], answer: 1, why: "Background tasks stop." },
        { q: "Disconnecting peripherals…", options: ["Increases draw", "Stops unnecessary power use", "Damages phone", "Is illegal"], answer: 1, why: "USB devices still draw power." },
        { q: "Efficient devices have…", options: ["Lower power use for same task", "Higher heat", "More fans", "Bigger plugs"], answer: 0, why: "Better performance per watt." },
        { q: "Renewable-energy data centres…", options: ["Use clean sources", "Burn coal", "Use no power", "Are illegal"], answer: 0, why: "Lower carbon impact." },
        { q: "Lowering brightness…", options: ["Always damages screen", "Saves substantial energy", "Disables Wi-Fi", "Reduces RAM"], answer: 1, why: "Display = biggest drain." },
        { q: "Disabling Wi-Fi when not needed…", options: ["Stops continuous radio activity", "Increases use", "Powers GPS", "Helps no one"], answer: 0, why: "Wi-Fi radio always scans." },
      ],
    },
    {
      id: "positive",
      code: "09",
      title: "Positive Environmental Impact",
      explanation:
        "Technology creates environmental problems but it can also solve them. Intelligent systems, monitoring tools and automation can cut waste, reduce emissions and protect wildlife at a scale impossible by hand.",
      bullets: [
        "Intelligent traffic systems reduce congestion and fuel use.",
        "Smart lighting systems lower electricity demand in cities.",
        "Environmental monitoring systems track pollution, deforestation and climate.",
        "Anti-poaching monitoring protects endangered wildlife.",
        "Regulation enforcement systems detect illegal dumping and emissions.",
      ],
      paragraphs: [
        "Smart traffic lights adapt to real-time flow, reducing the time cars sit idling at red lights — directly cutting urban pollution. Smart city lighting dims when streets are empty and brightens on demand.",
        "Sensor networks and satellite imaging now monitor rainforests, oceans and air quality across the planet. AI-powered cameras in national parks alert rangers to suspected poachers in real time, helping protect endangered species.",
      ],
      quiz: [
        { q: "Intelligent traffic systems…", options: ["Increase fuel use", "Reduce congestion and fuel use", "Ban cars", "Slow traffic always"], answer: 1, why: "Adaptive lights cut idling." },
        { q: "Smart lighting helps by…", options: ["Always on max", "Dimming when not needed", "Burning fuel", "Removing sensors"], answer: 1, why: "Demand-driven." },
        { q: "Environmental monitoring tracks…", options: ["Pollution, deforestation, climate", "Sports scores", "Cake recipes", "TV shows"], answer: 0, why: "Sensor networks + satellites." },
        { q: "Anti-poaching tech protects…", options: ["Stadiums", "Endangered wildlife", "Roads", "Phones"], answer: 1, why: "Cameras alert rangers." },
        { q: "Regulation enforcement systems can…", options: ["Detect illegal dumping/emissions", "Ban lightbulbs", "Plant trees", "Cool planet directly"], answer: 0, why: "Monitoring breaches of law." },
        { q: "Technology can both…", options: ["Harm and help the environment", "Only harm", "Only help", "Neither"], answer: 0, why: "Double-edged tool." },
        { q: "True/False: AI cameras can spot poachers.", options: ["True", "False"], answer: 0, why: "Real-world deployment." },
        { q: "Smart grids balance…", options: ["Renewable supply with demand", "Phones and tablets", "Music and movies", "Apps and games"], answer: 0, why: "Energy management." },
        { q: "Idling cars in traffic produce…", options: ["More pollution", "Less pollution", "Clean air", "Electricity"], answer: 0, why: "Wasted fuel = emissions." },
        { q: "Best summary: tech is…", options: ["A villain only", "A tool — depends how we use it", "Useless", "Always green"], answer: 1, why: "Impact depends on use." },
      ],
    },
  ],
  flashcards: [
    { category: "MANUFACTURE", front: "Raw materials in devices", back: "Copper, palladium (non-renewable) and arsenic (highly toxic)." },
    { category: "MANUFACTURE", front: "Mining damage", back: "Scars landscapes, creates waste, destroys habitats, damages ecosystems, pollutes." },
    { category: "MANUFACTURE", front: "Manufacturing energy", back: "Huge amounts, mostly from fossil fuels → CO₂ → climate change." },
    { category: "MANUFACTURE", front: "Waste water", back: "Polluted with toxic chemicals; can enter rivers/lakes and damage ecosystems." },
    { category: "ENERGY", front: "70/30 split", back: "Manufacture + disposal ≈ 70% of lifetime energy; use ≈ 30%." },
    { category: "ENERGY", front: "Where energy goes", back: "Production, operation, online storage in data centres, recycling, telecoms networks." },
    { category: "ENERGY", front: "Tech that saves energy", back: "Smart lighting, route planners, light sensors, intelligent systems." },
    { category: "DISPOSAL", front: "E-waste stats", back: "~50 Mt/year globally, only ~20% recycled." },
    { category: "DISPOSAL", front: "Toxic leaks", back: "Lead, mercury, cobalt → soil, groundwater, rivers." },
    { category: "DISPOSAL", front: "Health impact", back: "Poisoning, disease, long-term health problems near dump sites." },
    { category: "WEEE", front: "WEEE meaning", back: "Waste Electrical and Electronic Equipment regulations." },
    { category: "WEEE", front: "WEEE purpose", back: "Set recycling and collection targets, encourage recovery, reduce e-waste harm." },
    { category: "RECYCLING", front: "Recycling benefits", back: "Less chemical leak, lower fire risk, recover metals, less mining, recycle plastics, less air pollution." },
    { category: "REPLACEMENT", front: "Replacement cycle", back: "~3 years for phones; same for tablets, smartwatches, laptops." },
    { category: "REPLACEMENT", front: "Planned obsolescence", back: "Embedded batteries, glued/soldered parts, expensive spares, limited updates." },
    { category: "OWNERSHIP", front: "Responsible ownership", back: "Keep longer, buy second-hand, donate, recycle, reduce internet use, energy-efficient settings." },
    { category: "REDUCE", front: "Energy-saving actions", back: "Lower brightness, sleep mode, off Bluetooth/Wi-Fi/GPS, close apps, disconnect peripherals, efficient devices, renewable data centres." },
    { category: "POSITIVE", front: "Tech helping environment", back: "Smart traffic, smart lighting, environmental + anti-poaching monitoring, enforcement systems." },
  ],
};
