import type { TopicContent } from "./types";

export const legislation: TopicContent = {
  slug: "legislation",
  hero:
    "Three major UK laws set the rules of the digital world: the Data Protection Act 2018, the Computer Misuse Act 1990, and the Privacy and Electronic Communications Regulations 2003 (which cover cookies).",
  tags: ["DPA 2018", "CMA 1990", "PECR 2003", "PRINCIPLES", "RIGHTS", "OFFENCES", "COOKIES"],
  sections: [
    {
      id: "dpa-principles",
      code: "01",
      title: "DPA 2018 — Principles",
      explanation:
        "The Data Protection Act 2018 governs how organisations must handle personal data in the UK. It is built around seven core principles that every data controller must follow.",
      bullets: [
        "1. Lawfulness, fairness and transparency — process data legally and openly.",
        "2. Purpose limitation — only use data for the stated purpose.",
        "3. Data minimisation — collect only what is genuinely needed.",
        "4. Accuracy — keep data correct and up to date.",
        "5. Storage limitation — don't keep data longer than necessary.",
        "6. Security (integrity & confidentiality) — protect against loss, theft, unauthorised access.",
        "7. Accountability — organisations must prove they comply.",
      ],
      paragraphs: [
        "Lawfulness means there must be a legal basis (consent, contract, legal obligation, etc.) to process the data. Fairness means the use cannot harm the subject in unexpected ways. Transparency means the data subject is told what is being done.",
        "Data minimisation and storage limitation directly fight 'just-in-case' data hoarding. If a service doesn't truly need your phone number, it shouldn't collect it; if a record is no longer needed, it should be deleted.",
        "Accountability is the principle that ties everything together — controllers must keep records and be able to demonstrate compliance, not merely claim it. Breaches can lead to large fines from the Information Commissioner's Office (ICO).",
      ],
      quiz: [
        { q: "How many DPA principles?", options: ["3", "5", "7", "12"], answer: 2, why: "Seven." },
        { q: "'Don't keep data longer than needed' is…", options: ["Accuracy", "Storage limitation", "Lawfulness", "Accountability"], answer: 1, why: "Storage limitation." },
        { q: "Which is NOT a DPA principle?", options: ["Data minimisation", "Purpose limitation", "Maximum collection", "Security"], answer: 2, why: "Opposite of minimisation." },
        { q: "Accountability means…", options: ["Prove compliance", "Hide records", "Outsource", "Refuse audits"], answer: 0, why: "Demonstrate it, not just claim." },
        { q: "Purpose limitation requires…", options: ["Only using data for the stated purpose", "Using data however", "Selling data freely", "Keeping forever"], answer: 0, why: "Defined purpose only." },
        { q: "Accuracy means data should be…", options: ["Random", "Correct and up to date", "Encrypted always", "Public"], answer: 1, why: "Correct + current." },
        { q: "Lawfulness/fairness/transparency means…", options: ["Process legally, fairly, openly", "Hide processing", "Always free", "Random use"], answer: 0, why: "Combined principle." },
        { q: "Security principle protects against…", options: ["Loss / theft / unauthorised access", "Battery drain", "Slow Wi-Fi", "Sunburn"], answer: 0, why: "Integrity + confidentiality." },
        { q: "ICO can issue…", options: ["Large fines for breaches", "Free phones", "New laws", "Passports"], answer: 0, why: "Enforcement role." },
        { q: "Data minimisation = collect…", options: ["Everything possible", "Only what is needed", "Random samples", "Nothing"], answer: 1, why: "Necessary data only." },
      ],
    },
    {
      id: "dpa-rights",
      code: "02",
      title: "DPA 2018 — Data Subject Rights",
      explanation:
        "The DPA gives data subjects (you and me) a clear set of rights over how organisations use our data. Knowing them is the most practical part of the law.",
      bullets: [
        "Right to be informed — know what is collected and why.",
        "Right of access — request a copy of your data (Subject Access Request).",
        "Right to correct inaccurate data — fix errors in your records.",
        "Right to erase — request deletion ('right to be forgotten').",
        "Right to object to processing — stop certain uses (e.g. marketing).",
        "Right to withdraw consent — at any time, as easily as it was given.",
        "Right to restrict processing — pause use while a dispute is resolved.",
        "Right to reuse / data portability — receive data in a portable format.",
        "Right to complain to the Information Commissioner (ICO).",
      ],
      paragraphs: [
        "Subject Access Requests (SARs) let you see exactly what an organisation holds on you, usually within one month and free of charge. This is one of the most powerful tools the law gives ordinary people.",
        "Withdrawing consent must be as easy as giving it — the law explicitly forbids hiding the unsubscribe option. Similarly, portability lets you move your data to a competitor, increasing user power against lock-in.",
      ],
      quiz: [
        { q: "Right to access lets you…", options: ["Get a copy of your data", "Read others' data", "Edit company books", "Visit servers"], answer: 0, why: "Subject Access Request." },
        { q: "Right to erase is also called…", options: ["Right to be forgotten", "Right to spam", "Right to encrypt", "Right to download"], answer: 0, why: "Common informal name." },
        { q: "Right to data portability means…", options: ["Move data to another provider", "Print 100 copies", "Sell data yourself", "Hide your name"], answer: 0, why: "Receive in portable format." },
        { q: "Complaints can be made to…", options: ["The ICO", "Local football club", "ISP only", "Highway Agency"], answer: 0, why: "Information Commissioner." },
        { q: "Right to object means…", options: ["Stop certain processing", "Reject Wi-Fi", "Refuse food", "Quit the country"], answer: 0, why: "E.g. opt out of marketing." },
        { q: "Withdraw consent must be…", options: ["As easy as giving it", "Impossible", "Paid", "Once-only"], answer: 0, why: "Equally easy." },
        { q: "Right to restrict processing pauses use…", options: ["While a dispute is resolved", "Forever", "On weekends only", "Never"], answer: 0, why: "Temporary halt." },
        { q: "Right to correct allows you to…", options: ["Fix errors in records", "Edit others' data", "Delete the company", "Hack the server"], answer: 0, why: "Rectification." },
        { q: "True/False: you can object to processing.", options: ["True", "False"], answer: 0, why: "Listed right." },
        { q: "Right to be informed means…", options: ["Know what is collected and why", "Always be online", "Receive ads", "Get free data"], answer: 0, why: "Transparency to subject." },
      ],
    },
    {
      id: "cma",
      code: "03",
      title: "Computer Misuse Act 1990",
      explanation:
        "The CMA defines three computer-related criminal offences. It is the UK law that makes unauthorised access and damage to computer systems a crime.",
      bullets: [
        "Offence 1: Unauthorised access to a computer system.",
        "Offence 2: Unauthorised access with intent to commit a further crime.",
        "Offence 3: Unauthorised access to impair or damage systems (e.g. malware).",
        "Example O1: logging into a friend's account without permission.",
        "Example O2: gaining access to steal credit card details.",
        "Example O3: planting a virus or ransomware to damage systems.",
        "Intent is not required for Offence 1 — access alone is enough.",
      ],
      paragraphs: [
        "Logging into a friend's account 'as a joke' without permission is technically an offence under the CMA, even with no malicious intent. The unauthorised access itself is the crime.",
        "Offence 2 escalates the seriousness — using unauthorised access to commit fraud, theft, blackmail or similar. Offence 3 covers actively damaging systems, including releasing malware, ransomware, or wiping data.",
        "Penalties scale with offence: unauthorised access can mean up to 2 years, while malware that damages critical systems can carry sentences of 10+ years.",
      ],
      quiz: [
        { q: "How many main CMA offences?", options: ["2", "3", "5", "10"], answer: 1, why: "Three." },
        { q: "Offence 1 is…", options: ["Unauthorised access", "Theft", "Speeding", "Spam"], answer: 0, why: "Basic offence." },
        { q: "Planting malware is…", options: ["Offence 1", "Offence 2", "Offence 3", "None"], answer: 2, why: "Impair/damage systems." },
        { q: "Logging into someone's account without permission is…", options: ["Allowed", "Offence 1", "Only illegal at night", "Only illegal with money"], answer: 1, why: "Unauthorised access." },
        { q: "Stealing card details after access is…", options: ["Offence 2", "Offence 1 only", "Offence 3 only", "Not covered"], answer: 0, why: "Access + further crime." },
        { q: "True/False: Intent is needed for Offence 1.", options: ["True", "False"], answer: 1, why: "Access alone suffices." },
        { q: "Ransomware deployment is…", options: ["Offence 3", "Legal", "Offence 1 only", "Not covered"], answer: 0, why: "Damages systems." },
        { q: "CMA year?", options: ["1990", "1998", "2018", "2010"], answer: 0, why: "1990." },
        { q: "Which is NOT a CMA offence?", options: ["Unauthorised access", "Theft of physical property", "Access with intent for further crime", "Damaging systems"], answer: 1, why: "Different law." },
        { q: "CMA protects…", options: ["Computer systems and data integrity", "Cars", "Books", "Postal mail"], answer: 0, why: "Digital systems scope." },
      ],
    },
    {
      id: "cookies",
      code: "04",
      title: "Cookies & PECR 2003",
      explanation:
        "Cookies are small text files stored on a device by websites to recognise users and store preferences. Their use is regulated in the UK by the Privacy and Electronic Communications Regulations 2003.",
      bullets: [
        "A cookie = small text file stored on your device by a website.",
        "Cookies recognise returning users and store preferences.",
        "PECR 2003 = Privacy and Electronic Communications Regulations.",
        "Websites must inform users about cookies in use.",
        "Consent is required before non-essential cookies are set.",
        "Users may opt out of non-essential cookies at any time.",
        "Essential cookies (login session, shopping cart) do not require consent.",
        "Non-essential cookies (analytics, advertising) require explicit consent.",
      ],
      paragraphs: [
        "Cookies make modern websites usable — they remember you are logged in, keep items in your shopping cart and store language settings. Without them, every click would feel like visiting the site for the first time.",
        "The cookie banners you see on every website are the legal mechanism for informing users and getting consent under PECR. The DPA 2018 also applies because cookie data is usually personal data, so both laws work together.",
      ],
      quiz: [
        { q: "What is a cookie?", options: ["A virus", "Small text file stored by a website", "Browser plugin", "An OS"], answer: 1, why: "Definition." },
        { q: "Cookies are regulated in the UK by…", options: ["CMA 1990", "PECR 2003", "DPA 2018 only", "WEEE"], answer: 1, why: "Privacy and Electronic Communications Regs." },
        { q: "Before non-essential cookies, websites need…", options: ["Google permission", "User consent", "Nothing", "A cookie licence"], answer: 1, why: "PECR consent rule." },
        { q: "Cookies store…", options: ["Preferences and session info", "Your DNA", "Cake recipes", "Bluetooth signals"], answer: 0, why: "Preferences + state." },
        { q: "Essential cookies include…", options: ["Login session, shopping cart", "Ad trackers", "Spyware", "Adware"], answer: 0, why: "Required for function." },
        { q: "Users can…", options: ["Opt out of non-essential cookies", "Never block them", "Only on Tuesdays", "Only on phones"], answer: 0, why: "Opt-out allowed." },
        { q: "Cookie banners exist because…", options: ["Legal duty to inform + consent", "Adverts", "Free cookies", "Decoration"], answer: 0, why: "Compliance." },
        { q: "Cookies stored on…", options: ["User's device", "Server only", "The Moon", "The keyboard"], answer: 0, why: "Client side." },
        { q: "Which is NOT a cookie purpose?", options: ["Remembering preferences", "Tracking analytics", "Booting the OS", "Targeted ads"], answer: 2, why: "Cookies don't boot OS." },
        { q: "Cookie law year (UK)?", options: ["1990", "2003", "2018", "1998"], answer: 1, why: "PECR 2003." },
      ],
    },
  ],
  flashcards: [
    { category: "DPA", front: "Seven DPA principles", back: "Lawfulness/fairness/transparency, purpose limitation, data minimisation, accuracy, storage limitation, security, accountability." },
    { category: "DPA", front: "Data subject rights", back: "Be informed, access, correct, erase, object, withdraw consent, restrict, reuse (portability), complain to ICO." },
    { category: "DPA", front: "ICO", back: "Information Commissioner's Office — UK regulator that enforces DPA and PECR." },
    { category: "CMA", front: "Three CMA offences", back: "Unauthorised access; access with intent for further crime; access to impair/damage systems." },
    { category: "CMA", front: "CMA examples", back: "Logging into another's account; stealing card details after access; planting malware." },
    { category: "COOKIES", front: "Cookie", back: "Small text file stored by a website on the user's device to recognise users and store preferences." },
    { category: "COOKIES", front: "PECR 2003", back: "UK cookie law: inform users, get consent for non-essential cookies, allow opt-out." },
    { category: "COOKIES", front: "Essential vs non-essential cookies", back: "Essential (login, basket) need no consent; non-essential (analytics, ads) require explicit consent." },
  ],
};
