import type { TopicContent } from "./types";

export const protectingSystems: TopicContent = {
  slug: "protecting-systems",
  hero:
    "Every threat has a counter-measure. This module covers the layered defences that keep modern systems safe — authentication, encryption, firewalls, antivirus, backups, RAID and the human policies that hold it all together.",
  tags: ["AUTH", "ENCRYPTION", "FIREWALL", "ANTIVIRUS", "BACKUPS", "RAID", "AUP"],
  sections: [
    {
      id: "auth",
      code: "01",
      title: "Authentication & Access Control",
      explanation:
        "Authentication proves who a user is. Access control then decides what they are allowed to do. Together they form the front door of every secure system.",
      bullets: [
        "Strong passwords: long, mixed characters, not reused.",
        "Multi-factor authentication (MFA): something you know + have + are.",
        "Biometric authentication: fingerprint, face, iris, voice.",
        "Two-step verification: password + one-time code by SMS or app.",
        "Account lockout after repeated failures defeats brute force.",
        "Principle of least privilege: users get the minimum access needed.",
        "Role-based access control (RBAC): permissions assigned by role.",
      ],
      paragraphs: [
        "A strong password (12+ characters, mixed types) takes practically forever to brute force, but it is useless if reused on another site that is breached — credential stuffing relies on this. MFA solves the problem by requiring a second factor.",
        "Biometrics are convenient (no password to remember) but cannot be 'changed' if leaked — a stolen fingerprint scan is yours forever. Least privilege limits the damage if an account is compromised: a junior account stolen cannot grant admin powers.",
      ],
      quiz: [
        { q: "MFA = something you know + …", options: ["have + are", "say + do", "buy + sell", "watch + read"], answer: 0, why: "Three factor categories." },
        { q: "Biometric example?", options: ["Fingerprint", "Password", "Username", "Email"], answer: 0, why: "Physical trait." },
        { q: "Least privilege means…", options: ["Minimum access needed", "Full admin always", "No access", "Random access"], answer: 0, why: "Limits blast radius." },
        { q: "Account lockout defeats…", options: ["Brute force", "Rain", "Cold", "Wi-Fi"], answer: 0, why: "Stops repeated guessing." },
        { q: "Strong password traits?", options: ["Long + mixed + unique", "Short + repeated", "Just your name", "Password123"], answer: 0, why: "Length and uniqueness." },
        { q: "Two-step verification adds…", options: ["A second factor (code)", "More ads", "Bigger fonts", "More RAM"], answer: 0, why: "OTP or app code." },
        { q: "RBAC means…", options: ["Role-based access control", "Random byte access", "RAM-based audio", "Reverse boot"], answer: 0, why: "Permissions per role." },
        { q: "Biometric downside?", options: ["Cannot be changed if leaked", "Always works perfectly", "Free hardware", "Fast Wi-Fi"], answer: 0, why: "Stolen forever." },
        { q: "MFA defeats…", options: ["Credential stuffing + simple phishing", "Lightning", "Heat", "Rain"], answer: 0, why: "Second factor stops reuse." },
        { q: "Best practice?", options: ["Strong unique pw + MFA + least privilege", "Same pw everywhere", "No passwords", "Stickers on monitor"], answer: 0, why: "Layered." },
      ],
    },
    {
      id: "encryption",
      code: "02",
      title: "Encryption",
      explanation:
        "Encryption scrambles data so only authorised people with the right key can read it. It protects data both 'at rest' (on disk) and 'in transit' (over networks).",
      bullets: [
        "Plaintext = readable data; ciphertext = encrypted data.",
        "Symmetric encryption: same key encrypts and decrypts (fast, e.g. AES).",
        "Asymmetric encryption: public + private key pair (e.g. RSA).",
        "Public key encrypts; only matching private key can decrypt.",
        "HTTPS uses encryption (TLS) to protect web traffic.",
        "Encryption at rest protects stored data (disk, database).",
        "Encryption in transit protects data moving across networks.",
        "Strong encryption is useless if keys are leaked or weak.",
      ],
      paragraphs: [
        "Symmetric encryption is fast and used for bulk data (your hard drive, your phone storage). The challenge is sharing the secret key safely. Asymmetric encryption solves the key-sharing problem with public/private key pairs.",
        "HTTPS combines both: asymmetric encryption sets up the secure channel, then symmetric encryption protects the actual traffic. The padlock icon in a browser indicates this TLS-secured connection.",
      ],
      quiz: [
        { q: "Plaintext becomes…", options: ["Ciphertext when encrypted", "Audio", "Image", "Binary only"], answer: 0, why: "Encryption transforms readable to scrambled." },
        { q: "Symmetric encryption uses…", options: ["Same key both ways", "Two different keys", "No keys", "Random keys daily"], answer: 0, why: "Shared key." },
        { q: "Asymmetric encryption uses…", options: ["Public + private key pair", "One key only", "No keys", "Wi-Fi only"], answer: 0, why: "Key pair." },
        { q: "HTTPS uses…", options: ["Encryption (TLS)", "Plaintext", "FTP only", "Mail only"], answer: 0, why: "TLS encrypts web traffic." },
        { q: "Encryption at rest protects…", options: ["Stored data", "Live calls only", "Battery", "Screen"], answer: 0, why: "Disk/database." },
        { q: "Encryption in transit protects…", options: ["Data moving over networks", "Furniture", "Cars", "Plants"], answer: 0, why: "Network traffic." },
        { q: "AES is…", options: ["A symmetric algorithm", "Wi-Fi router", "Hard disk", "Antivirus"], answer: 0, why: "Symmetric block cipher." },
        { q: "RSA is…", options: ["Asymmetric algorithm", "Hashing only", "Database", "OS"], answer: 0, why: "Public-key cipher." },
        { q: "If a key leaks…", options: ["Encryption protection is broken", "Nothing happens", "More speed", "Cleaner code"], answer: 0, why: "Confidentiality lost." },
        { q: "Public key is used to…", options: ["Encrypt; private decrypts", "Decrypt; public can read all", "Sign hardware", "Print labels"], answer: 0, why: "Public encrypts." },
      ],
    },
    {
      id: "firewall-av",
      code: "03",
      title: "Firewalls & Antivirus",
      explanation:
        "Firewalls control network traffic in and out of a system; antivirus / anti-malware detects and removes malicious software. Together they form the perimeter and the immune system.",
      bullets: [
        "Firewall = filters traffic against a rule set (allow/deny).",
        "Packet-filtering firewall: inspects source/destination/port.",
        "Stateful firewall: tracks active connections.",
        "Application firewall: understands specific protocols (e.g. HTTP).",
        "Blocks unauthorised inbound connections + suspicious outbound.",
        "Antivirus uses signature detection: matches known malware patterns.",
        "Heuristic analysis: detects new/unknown malware by suspicious behaviour.",
        "Sandboxing: runs suspicious code in an isolated environment to observe it.",
        "Regular updates are essential — new malware appears daily.",
      ],
      paragraphs: [
        "Signature detection is fast but blind to brand-new malware. Heuristic analysis fills the gap by looking at what a program does — does it try to overwrite system files, contact suspicious servers, encrypt user data? Sandboxing runs the suspect inside a safe virtual environment to watch its behaviour without risk.",
        "Firewalls block unauthorised inbound connections (e.g. attackers scanning your IP) and can also block outbound connections (e.g. malware trying to phone home). Modern systems combine network firewalls (at the router) with host-based firewalls (on each device).",
      ],
      quiz: [
        { q: "Firewall filters…", options: ["Network traffic", "Sunlight", "Sound", "Plants"], answer: 0, why: "Allow/deny rules." },
        { q: "Antivirus signature detection matches…", options: ["Known malware patterns", "Random text", "Wi-Fi", "Battery"], answer: 0, why: "Database of signatures." },
        { q: "Heuristic analysis catches…", options: ["New/unknown malware by behaviour", "Only old malware", "Only files >1 GB", "Hardware bugs"], answer: 0, why: "Behaviour-based." },
        { q: "Sandboxing runs suspect code…", options: ["In an isolated environment", "On the kernel", "Directly on disk", "On the cloud admin"], answer: 0, why: "Safe observation." },
        { q: "Stateful firewall tracks…", options: ["Active connections", "Battery level", "RAM colour", "USB drives"], answer: 0, why: "Connection state." },
        { q: "Firewalls can block…", options: ["Inbound + suspicious outbound traffic", "Lightning", "Heat", "Sound"], answer: 0, why: "Both directions." },
        { q: "Why update antivirus?", options: ["New malware appears daily", "Better colours", "Faster Wi-Fi", "Cleaner code"], answer: 0, why: "Signature DB refresh." },
        { q: "Packet-filtering firewall looks at…", options: ["Source/destination/port", "Battery temp", "Camera lens", "Screen size"], answer: 0, why: "Header inspection." },
        { q: "Antivirus can…", options: ["Detect, quarantine, remove malware", "Build hardware", "Mine ore", "Print PDF"], answer: 0, why: "Core functions." },
        { q: "Best protection combines…", options: ["Firewall + AV + updates + user awareness", "Just AV", "Just firewall", "Stickers"], answer: 0, why: "Layered defence." },
      ],
    },
    {
      id: "backups-raid",
      code: "04",
      title: "Backups & RAID",
      explanation:
        "Backups protect data against loss, theft and ransomware. RAID protects against drive failure by spreading data across multiple disks. Both are about availability.",
      bullets: [
        "Full backup — copy everything (slow, big, simple to restore).",
        "Incremental backup — copy what changed since the LAST backup (fast, complex restore).",
        "Differential backup — copy what changed since the last FULL backup.",
        "3-2-1 rule: 3 copies, 2 different media, 1 offsite.",
        "Offsite / cloud backups protect against fire, theft, ransomware.",
        "RAID 0 — stripes data across drives (speed, NO redundancy).",
        "RAID 1 — mirrors data across two drives (full redundancy, half capacity).",
        "RAID 5 — stripes with parity (good balance of speed, capacity, redundancy).",
        "RAID 10 — combines striping + mirroring (high speed + redundancy).",
        "RAID is NOT a backup — it does not protect against deletion, ransomware or theft.",
      ],
      paragraphs: [
        "Backups are about recoverability. A full backup is simple — one file restores everything. Incremental backups are smaller and faster but to restore you need the last full backup PLUS every incremental since. Differential sits in between: faster than full, simpler than incremental.",
        "The 3-2-1 rule (3 copies on 2 different media with 1 offsite) survives almost any single disaster — fire, flood, theft or ransomware. Cloud backups make the 'offsite' part easy.",
        "RAID protects against hardware failure: if a disk dies, the array keeps running. RAID 1 mirrors, RAID 5 uses parity. But if you delete a file by mistake or ransomware encrypts it, RAID happily mirrors the destruction. That's why RAID is not a backup.",
      ],
      quiz: [
        { q: "Full backup copies…", options: ["Everything", "Only changes", "Random files", "Nothing"], answer: 0, why: "Complete copy." },
        { q: "Incremental backup copies…", options: ["Changes since last backup", "Everything every time", "Nothing", "Audio only"], answer: 0, why: "Smallest delta." },
        { q: "Differential backup copies…", options: ["Changes since last FULL backup", "Changes since any backup", "Only photos", "Only video"], answer: 0, why: "Cumulative since full." },
        { q: "3-2-1 rule = …", options: ["3 copies, 2 media, 1 offsite", "3 backups every 2 days +1 user", "3 RAID disks +2 SSD +1 HDD", "Random"], answer: 0, why: "Standard rule." },
        { q: "RAID 1 means…", options: ["Mirroring", "Striping", "Parity", "Nothing"], answer: 0, why: "Two-disk mirror." },
        { q: "RAID 0 provides…", options: ["Speed, no redundancy", "Full redundancy", "Best of both", "Backup"], answer: 0, why: "Striped only." },
        { q: "RAID 5 uses…", options: ["Striping + parity", "Mirror only", "Triple mirror", "No parity"], answer: 0, why: "Distributed parity." },
        { q: "Is RAID a backup?", options: ["No", "Yes", "Only RAID 1", "Only RAID 5"], answer: 0, why: "Doesn't protect against deletion/ransomware." },
        { q: "Offsite backup helps against…", options: ["Fire, theft, ransomware at the main site", "Nothing", "Battery wear", "Screen burn"], answer: 0, why: "Geographic redundancy." },
        { q: "Cloud backup is…", options: ["Often the 'offsite' copy in 3-2-1", "Forbidden", "Always RAID 0", "Mirror only"], answer: 0, why: "Easy offsite option." },
      ],
    },
    {
      id: "aup",
      code: "05",
      title: "AUP & Human Policies",
      explanation:
        "Technology alone cannot stop attacks. An Acceptable Use Policy (AUP) sets the rules for how staff and students may use systems, with training and monitoring to back it up.",
      bullets: [
        "AUP = Acceptable Use Policy — agreed rules for using IT systems.",
        "Defines permitted activities (work, study) and prohibited ones (illegal, offensive content).",
        "Sets password rules: length, complexity, change frequency.",
        "Covers data handling: where data may be stored, USBs, personal devices.",
        "Covers internet use: streaming, downloads, social media at work.",
        "Specifies consequences for breach (warnings, dismissal, prosecution).",
        "Regular staff training keeps policies current and effective.",
        "Monitoring + logging detect breaches and support investigations.",
      ],
      paragraphs: [
        "An AUP makes responsibilities explicit. New staff sign it on joining, agreeing not to share passwords, install unapproved software or visit prohibited sites. Training reinforces the AUP with practical guidance — how to spot phishing, how to report incidents.",
        "Logging and monitoring complete the picture. If a breach happens, logs show who did what and when. Knowing they're being logged also deters most insider misuse — most people won't risk dismissal or prosecution.",
      ],
      quiz: [
        { q: "AUP =", options: ["Acceptable Use Policy", "Anti-Update Patch", "Adware-Use Permit", "Auto USB Pass"], answer: 0, why: "Standard expansion." },
        { q: "AUP sets…", options: ["Rules for using IT systems", "WiFi prices", "Hardware brands", "Coffee orders"], answer: 0, why: "Use rules." },
        { q: "AUP usually covers…", options: ["Passwords, data handling, internet use", "Snacks only", "Weather", "Plants"], answer: 0, why: "Broad usage rules." },
        { q: "Consequences in AUP may include…", options: ["Warnings, dismissal, prosecution", "Free phones", "Holiday bonus", "Free Wi-Fi"], answer: 0, why: "Enforcement." },
        { q: "Why train staff?", options: ["Keep policies effective + spot attacks", "Make tea", "Tune pianos", "Plant trees"], answer: 0, why: "Awareness." },
        { q: "Monitoring helps to…", options: ["Detect breaches + deter misuse", "Speed Wi-Fi", "Increase RAM", "Brighten screen"], answer: 0, why: "Visibility + deterrence." },
        { q: "AUP for passwords might set…", options: ["Length + complexity + change frequency", "Colour + font", "RAM size", "Screen size"], answer: 0, why: "Password policy." },
        { q: "AUP applies to…", options: ["All staff (and often students)", "Only IT", "Only directors", "Only visitors"], answer: 0, why: "Org-wide." },
        { q: "Best security combines…", options: ["Tech + policy + training", "Just antivirus", "Just firewall", "Stickers"], answer: 0, why: "People + process + tech." },
        { q: "True/False: AUP can deter insider misuse.", options: ["True", "False"], answer: 0, why: "Clear rules + monitoring." },
      ],
    },
  ],
  flashcards: [
    { category: "AUTH", front: "MFA factors", back: "Something you know (password) + have (token/phone) + are (biometric)." },
    { category: "AUTH", front: "Least privilege", back: "Each user gets only the minimum access needed — limits damage if account is compromised." },
    { category: "ENCRYPTION", front: "Symmetric vs asymmetric", back: "Symmetric = one shared key (fast, AES); asymmetric = public+private key pair (RSA)." },
    { category: "ENCRYPTION", front: "At rest vs in transit", back: "At rest = stored data (disk); in transit = data moving across networks (HTTPS/TLS)." },
    { category: "FIREWALL", front: "Firewall job", back: "Filter network traffic against rules — block unauthorised inbound + suspicious outbound." },
    { category: "ANTIVIRUS", front: "Signature vs heuristic", back: "Signature matches known patterns; heuristic detects unknown malware by behaviour." },
    { category: "ANTIVIRUS", front: "Sandboxing", back: "Run suspect code in an isolated environment to observe it without risk to host system." },
    { category: "BACKUPS", front: "Backup types", back: "Full (everything), Incremental (since last backup), Differential (since last full)." },
    { category: "BACKUPS", front: "3-2-1 rule", back: "3 copies of data, 2 different media, 1 stored offsite." },
    { category: "RAID", front: "RAID summary", back: "0 = stripe (speed only), 1 = mirror, 5 = stripe + parity, 10 = stripe + mirror." },
    { category: "RAID", front: "Is RAID a backup?", back: "NO — RAID protects against drive failure, NOT against deletion, ransomware or theft." },
    { category: "AUP", front: "AUP", back: "Acceptable Use Policy — agreed rules for using IT systems, with consequences for breach." },
  ],
};
