import type { TopicContent } from "./types";

export const threats: TopicContent = {
  slug: "threats",
  hero:
    "Digital systems face constant attack: malware, social engineering, brute force, denial of service and weak access control. This module catalogues the main threats every IGCSE student needs to recognise.",
  tags: ["MALWARE", "SOCIAL ENGINEERING", "BRUTE FORCE", "DOS", "INSIDER", "WEAK"],
  sections: [
    {
      id: "malware",
      code: "01",
      title: "Malware",
      explanation:
        "Malware (malicious software) is any program designed to damage, disrupt or gain unauthorised access to systems. It comes in many flavours — each with a different goal.",
      bullets: [
        "Virus — attaches to legitimate files, spreads when the file runs, often damages data.",
        "Worm — self-replicating; spreads across networks without needing a host file.",
        "Trojan — disguised as legitimate software; opens a back door once installed.",
        "Ransomware — encrypts files and demands payment for the decryption key.",
        "Spyware — secretly monitors activity (keystrokes, screens, cameras).",
        "Adware — bombards the user with ads; may track behaviour.",
        "Rootkit — hides deep in the OS, giving attackers persistent admin access.",
        "Keylogger — records every keystroke including passwords.",
      ],
      paragraphs: [
        "Viruses need a user to run an infected file (e.g. an email attachment). Worms are more dangerous because they self-propagate across networks once a single device is infected — the WannaCry worm infected hundreds of thousands of machines in 2017.",
        "Trojans rely on social trickery: the user installs what they think is a useful program and unknowingly opens a back door. Ransomware combines a trojan delivery with strong encryption — paying the ransom is no guarantee the attacker hands over the key.",
        "Spyware, keyloggers and rootkits all aim to stay hidden. Spyware exfiltrates data; keyloggers capture credentials; rootkits give long-term, low-level control of the machine.",
      ],
      quiz: [
        { q: "A worm differs from a virus because it…", options: ["Self-replicates across networks", "Needs a host file", "Is harmless", "Is hardware"], answer: 0, why: "Self-propagating." },
        { q: "Ransomware…", options: ["Encrypts files + demands payment", "Cleans your PC", "Speeds up Wi-Fi", "Defrags drives"], answer: 0, why: "Definition." },
        { q: "A Trojan…", options: ["Disguises itself as legitimate software", "Self-spreads always", "Is hardware", "Cleans data"], answer: 0, why: "Disguise + back door." },
        { q: "Spyware…", options: ["Monitors activity secretly", "Cleans malware", "Defrags drives", "Speeds RAM"], answer: 0, why: "Hidden monitoring." },
        { q: "Keylogger records…", options: ["Every keystroke", "Free music", "Battery life", "Weather"], answer: 0, why: "Captures passwords too." },
        { q: "Rootkit gives attackers…", options: ["Persistent admin access", "Free Wi-Fi", "Faster CPU", "More RAM"], answer: 0, why: "Deep, hidden control." },
        { q: "Adware mainly…", options: ["Shows / tracks ads", "Encrypts files", "Cleans malware", "Backs up data"], answer: 0, why: "Ad-driven." },
        { q: "True/False: paying ransomware always gets your files back.", options: ["True", "False"], answer: 1, why: "No guarantee." },
        { q: "Virus typically spreads when…", options: ["The infected file is run", "PC is unplugged", "Wi-Fi is off", "Phone rings"], answer: 0, why: "User executes host file." },
        { q: "Which is NOT malware?", options: ["Antivirus scanner", "Trojan", "Worm", "Ransomware"], answer: 0, why: "Antivirus fights malware." },
      ],
    },
    {
      id: "social-engineering",
      code: "02",
      title: "Social Engineering",
      explanation:
        "Social engineering attacks target people, not technology. They trick users into giving up credentials, clicking malicious links or making payments to attackers.",
      bullets: [
        "Phishing — fake emails impersonating trusted organisations (banks, schools).",
        "Spear phishing — phishing aimed at one specific person, often using personal details.",
        "Vishing — phishing by phone call.",
        "Smishing — phishing by SMS text.",
        "Pretexting — inventing a scenario to extract information (e.g. fake IT helpdesk).",
        "Baiting — leaving a malicious USB stick for someone to plug in.",
        "Shoulder surfing — watching someone enter a password or PIN.",
        "Tailgating — following an authorised person through a secure door.",
      ],
      paragraphs: [
        "Phishing emails imitate banks or services with urgent language ('Your account will be closed!') and a link to a fake site that captures credentials. Spear phishing is far more dangerous because the attacker has researched the target and writes a convincing, personalised message.",
        "Pretexting attacks often impersonate IT support, asking the user to 'verify' a password. Tailgating bypasses physical security: holding the door open for a stranger feels polite but can let an attacker into the building.",
      ],
      quiz: [
        { q: "Phishing attacks target…", options: ["People (via fake messages)", "Routers", "Disks", "CPUs"], answer: 0, why: "Social engineering." },
        { q: "Vishing is phishing by…", options: ["Phone call", "SMS", "Email", "USB"], answer: 0, why: "Voice phishing." },
        { q: "Smishing is phishing by…", options: ["SMS text", "Phone call", "Email", "USB"], answer: 0, why: "SMS phishing." },
        { q: "Spear phishing is…", options: ["Highly targeted phishing", "Random spam", "Antivirus", "Backup"], answer: 0, why: "Personalised attack." },
        { q: "Tailgating is…", options: ["Following an authorised person through a secure door", "Email scam", "USB drop", "Phone call"], answer: 0, why: "Physical bypass." },
        { q: "Shoulder surfing is…", options: ["Watching someone type a password", "Surfing the web", "Beach sport", "Sound attack"], answer: 0, why: "Observation attack." },
        { q: "Baiting uses…", options: ["Malicious USB sticks people pick up", "Honest emails", "Free Wi-Fi", "Hardware updates"], answer: 0, why: "Curiosity trap." },
        { q: "Pretexting means…", options: ["Inventing a scenario to extract info", "Encrypting files", "Backing up data", "Updating apps"], answer: 0, why: "Fake context." },
        { q: "Best defence vs phishing?", options: ["User awareness + checking links + MFA", "Bigger fonts", "Faster Wi-Fi", "More RAM"], answer: 0, why: "Combined defences." },
        { q: "Social engineering exploits…", options: ["Human trust and behaviour", "CPU speed", "RAM size", "Screen brightness"], answer: 0, why: "Targets people." },
      ],
    },
    {
      id: "attacks",
      code: "03",
      title: "Brute Force, DoS & Insider Threats",
      explanation:
        "Some attacks try to crack their way in (brute force), some try to knock systems offline (denial of service), and some come from inside the organisation itself.",
      bullets: [
        "Brute force — trying every possible password until one works.",
        "Dictionary attack — trying common words/phrases first.",
        "Credential stuffing — reusing leaked passwords on other sites.",
        "Denial of Service (DoS) — flooding a system to make it unavailable.",
        "Distributed DoS (DDoS) — same idea but from thousands of devices (botnet).",
        "Insider threat — a current/former employee misusing access.",
        "Accidental insider — a user who clicks a phishing link or misconfigures a system.",
        "Weak / default passwords and unpatched software are major risk factors.",
      ],
      paragraphs: [
        "Brute force is slow against strong passwords but devastating against weak ones. Adding length and symbols turns minutes of attack into millions of years. Dictionary attacks short-cut the process by trying 'password123' first.",
        "DoS attacks can take a website offline by overwhelming its servers; DDoS uses a botnet of compromised devices to amplify the attack to millions of requests per second. Even short outages can cost businesses millions.",
        "Not every attacker is outside. Insider threats — disgruntled employees, contractors, or careless staff — already have legitimate access, which makes them very dangerous and hard to detect.",
      ],
      quiz: [
        { q: "Brute force tries…", options: ["Every possible password", "Just one password", "Random Wi-Fi", "No passwords"], answer: 0, why: "Exhaustive search." },
        { q: "Dictionary attack uses…", options: ["Common words / phrases", "Only numbers", "Only emoji", "Brute audio"], answer: 0, why: "Likely guesses first." },
        { q: "Credential stuffing…", options: ["Reuses leaked passwords elsewhere", "Stuffs servers", "Sends spam", "Encrypts data"], answer: 0, why: "Same password, many sites." },
        { q: "DoS attack…", options: ["Floods system to make it unavailable", "Cleans system", "Encrypts files", "Backs up data"], answer: 0, why: "Availability attack." },
        { q: "DDoS uses…", options: ["A botnet of many devices", "One PC", "USB sticks", "Disks"], answer: 0, why: "Distributed flood." },
        { q: "Insider threat is…", options: ["Current/former staff misusing access", "Outside hacker", "Software bug", "Weather"], answer: 0, why: "Internal source." },
        { q: "Accidental insider example?", options: ["User clicks phishing link", "USB drive", "Stolen laptop", "Lightning"], answer: 0, why: "Careless, not malicious." },
        { q: "Strong password defence beats…", options: ["Brute force + dictionary", "Heat", "Cold", "Rain"], answer: 0, why: "Length + complexity." },
        { q: "DoS attacks affect…", options: ["Availability", "Battery life", "Screen colour", "RAM brand"], answer: 0, why: "Service uptime." },
        { q: "Unpatched software risks…", options: ["Known exploits being used against you", "Better speed", "More RAM", "Cleaner code"], answer: 0, why: "Missing security fixes." },
      ],
    },
  ],
  flashcards: [
    { category: "MALWARE", front: "Virus vs worm", back: "Virus needs a host file + user action; worm self-replicates across networks." },
    { category: "MALWARE", front: "Trojan", back: "Malware disguised as legitimate software; opens a back door once run." },
    { category: "MALWARE", front: "Ransomware", back: "Encrypts files and demands payment for the decryption key." },
    { category: "MALWARE", front: "Spyware / keylogger / rootkit", back: "Hidden monitoring / keystroke capture / persistent low-level admin access." },
    { category: "SOCIAL", front: "Phishing variants", back: "Phishing (email), spear phishing (targeted), vishing (voice), smishing (SMS)." },
    { category: "SOCIAL", front: "Physical social engineering", back: "Shoulder surfing, tailgating, baiting (malicious USB)." },
    { category: "SOCIAL", front: "Pretexting", back: "Inventing a fake scenario (e.g. IT support) to extract information." },
    { category: "ATTACKS", front: "Brute force", back: "Try every possible password; defeated by strong passwords + MFA + rate limits." },
    { category: "ATTACKS", front: "DoS vs DDoS", back: "DoS = flood from one source; DDoS = flood from many compromised devices (botnet)." },
    { category: "ATTACKS", front: "Insider threat", back: "Current or former staff with legitimate access — malicious or accidental." },
  ],
};
